import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import StoreProvider from "./StoreProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ margin: 0, padding: 0}}>
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{
  position: 'fixed',
  top: 0,
  left: 0,
  width: '100vw',
  height: '100vh',
  overflow: 'auto',
  // overflow: 'hidden',
  margin: 0,
  padding: 0,
  zIndex: 9999,
  backgroundColor: 'red' // Для визуальной проверки
}}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
